# Generated by Django 3.0.3 on 2022-05-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='link',
        ),
    ]
