# Generated by Django 3.0.3 on 2022-05-29 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_auto_20220529_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
